### ISSUE TITLE
Can't catkin_make after commit c04e286

### ISSUE THREAD

**Issue by hackan88** [mfueller/vrep_youbot_plugin#4]
catkin_make no longer works after commit c04e286 ("backup"), had to go back to f6d95b9.

Errors: (I've removed parts of the path name)
vrep_youbot_plugin/src/ros/callback/ClockCallback.cpp:40:2: error: ‘ClockPluglet’ was not declared in this scope
  ClockPluglet* pluglet = new ClockPluglet();
  ^
vrep_youbot_plugin/src/ros/callback/ClockCallback.cpp:40:16: error: ‘pluglet’ was not declared in this scope
  ClockPluglet* pluglet = new ClockPluglet();
                ^
vrep_youbot_plugin/src/ros/callback/ClockCallback.cpp:40:30: error: expected type-specifier before ‘ClockPluglet’
  ClockPluglet* pluglet = new ClockPluglet();
                              ^
vrep_youbot_plugin/src/ros/callback/ClockCallback.cpp:40:30: error: expected ‘;’ before ‘ClockPluglet’
vrep_youbot_plugin/src/ros/callback/ClockCallback.cpp:43:8: error: ‘vrep::VRepPlugletRegistry’ has not been declared
  vrep::VRepPlugletRegistry::getInstance()->getPluglets().push_back(pluglet);

**Comment by Ram2301** [comment]
Have some problem too:c

**Comment by mazaaa** [comment]
I get an  >> Invoking "make" failed << error after using catkin_make. If I use the older (f6d95b9) commit, it works, but then I cannot use the plugin with the newest vrep version V3.2.3 rev4 (compatibility issue) and all the added features are not available too.

It seems like there is an error in vrep_youbot_plugin/src/ros/callback/ClockCallback.cpp but I'm not sure if this causes the main error.

Any ideas?

I use ROS Hydro and Ubuntu 12.04.

**Comment by mfueller** [comment]
The ClockPluglet error should be gone with commit 01f5106fb454272fb90497f1ac6507aac5f7c047
Since I do not have a proper Ubuntu/ROS/V-rep system anymore, I could not test it.
Please test and try to fix the remaining error and create a pull request

**Comment by mazaaa** [comment]
Thanks for the fast response! The simulation starts and the states are published successfully after commit 01f5106. The simulation does not response to rostopic pub commands though. I will try to find what the problem is. 

I've seen that you use these topics to communicate:
/arm_controller/position_command
/gripper_controller/position_command
/cmd_vel

Are the FollowJointTrajectory topics also accessible?
